name: 'Compile Mermaid'

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep -e './test*\.md$'  | xargs)"

      - name: mermaid files changed
        run: |
          echo ${{ steps.getfile.outputs.files }}

      - name: compile mermaid
        uses: neenjaw/compile-mermaid-markdown-action@0.3.0
        with:
          files: ${{ steps.getfile.outputs.files }}
          output: 'diagrams'
        env:
          HIDE_CODEBLOCKS: 1
          ABSOLUTE_IMAGE_LINKS: 1

      - name: Commit updated package versions
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Sequence diagrams"
          git push


